config/routes.rb
Rails.application.routes.draw do
  root 'zombies#index'
  devise_for :users, controllers:{
    sessions: 'users/sessions'
  }
  resources :zombies do
  	resources :brains
  end

  get '/cerebros',to:'brains#index',as:'brains'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  before_action :set_zombie, only: [:show, :edit, :update, :destroy]

  # GET /zombies
  # GET /zombies.json
  def index
    if current_user.role == 'Contribuidor'
      @zombies = Zombie.where(user_id: current_user.id)
    else
      @zombies = Zombie.all
    end
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
  end

  # GET /zombies/new
  def new
    @zombie = Zombie.new
  end

  # GET /zombies/1/edit
  def edit
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(zombie_params)
    @zombie.user_id = current_user.id
    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render :show, status: :created, location: @zombie }
      else
        format.html { render :new }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zombies/1
  # PATCH/PUT /zombies/1.json
  def update
    respond_to do |format|
      if @zombie.update(zombie_params)
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { render :show, status: :ok, location: @zombie }
      else
        format.html { render :edit }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie.destroy
    respond_to do |format|
      format.html { redirect_to zombies_url, notice: 'Zombie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zombie
      @zombie = Zombie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zombie_params
      params.require(:zombie).permit(:name, :bio, :age,:email,:rotten,:avatar,:user_id)
    end
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/zombies/_form.html.erb
<%= form_for(zombie) do |f| %>
  <% if zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% zombie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
      <div class="large-6 column">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div class="large-6 column">
        <%= f.label :bio %>
        <%= f.text_area :bio %>
      </div>

      <div class="large-6 column">
        <%= f.label :age %>
        <%= f.number_field :age %>
      </div>

      <div class="large-6 column">
        <%= f.label :Email %>
        <%= f.text_field :email %>
      </div>

      <div class="large-6 column">
        <%= f.label :Rotten %>
        <%= f.check_box :rotten %>
      </div>

      <div class="large-6 column">
        <%= f.label :Avatar %>
        <%= f.file_field :avatar %>
      </div>
  </div>
      
  <Section class="row">
    <div class="small-4 columns">
      <div class="actions">
        <%= f.submit 'Aceptar',:class => "button round"%>
      </div>
    </div>
  </Section>

<% end %>

app/views/zombies/edit.html.erb
<h1>Editing Zombie</h1>

<%= render 'form', zombie: @zombie %>

<%= link_to 'Show', @zombie %> |
<%= link_to 'Back', zombies_path %>

app/views/zombies/index.html.erb
<h1>Zombies</h1>

<table>
  <thead>

    <tr>
      <th>Avatar</th>
      <th>Nombre</th>
      <th>Biografia</th>
      <th>Edad</th>
      <th>Email</th>
      <th>¿Podrido?</th>
      <th>Pertenece a:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zombies.each do |zombie| %>
      <tr>
        <td><%= image_tag(zombie.avatar_url, :width=> 75, :height =>75)%></td>
        <td><%= zombie.name %></td>
        <td><%= zombie.bio %></td>
        <td><%= zombie.age %></td>
        <td><%= zombie.email %></td>
        <td><%= zombie.rotten ? "Si":"No" %></td>
        <th><%= zombie.user_id ? User.where(id: zombie.user_id)[0].email : "no tiene dueño" %></th>
        <% if current_user.role != 'Subscriptor'%>
          <td><%= link_to 'Show', zombie, class: 'button'%></td>
          <td><%= link_to 'Edit', edit_zombie_path(zombie), class: 'button success' %></td>
          <% if current_user.role == 'Editor' %>
            <td><%= link_to 'Destroy', zombie, method: :delete, data: { confirm: 'Are you sure?' } , class: 'button alert'%></td>            
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/zombies/new.html.erb
<h1>New Zombie</h1>

<%= render 'form', zombie: @zombie %>

<%= link_to 'Back', zombies_path %>

app/views/zombies/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @zombie.name %>
</p>
<p>
  <strong>Avatar:</strong>
  <%= image_tag(@zombie.avatar_url, :width=> 300, :height =>300)%>
</p>
<p>
  <strong>Bio:</strong>
  <%= @zombie.bio %>
</p>

<p>
  <strong>Age:</strong>
  <%= @zombie.age %>
</p>

<p>
  <strong>Email:</strong>
  <%= @zombie.email %>
</p>

<p>
  <strong>Podrido:</strong>
  <%= @zombie.rotten %>
</p>

<%= link_to 'Edit', edit_zombie_path(@zombie) %> |
<%= link_to 'Back', zombies_path %>

<div id="brains">
  <%= render :partial => @zombie.brains.reverse %>
</div>

<%= form_for([@zombie,Brain.new],remote: true)do |f| %>
<div class="field">
    <%= f.label :flavor %>
    <%= f.text_field :flavor %>
  </div>

  <div class="field">
    <%= f.label :iq %>
    <%= f.number_field :iq %>
  </div>

    <div class="field">
    <%= f.label :fresh %>
    <%= f.check_box :fresh %>
  </div>

  <div class="actions">
    <%= f.submit"Add brains" %>
  </div>
  <% end %>